apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: capi-ocp-aws
  namespace: default
spec:
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AWSCluster
    name: capi-ocp-aws

---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSCluster
metadata:
  name: capi-ocp-aws
  namespace: default
spec:
  region: us-east-2

---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineSet
metadata:
  name: capi-ocp-aws-md-0
  namespace: default
spec:
  clusterName: capi-ocp-aws
  replicas: 1
  selector:
    matchLabels: 
      test: test
  template:
    metadata:
      labels:
        test: test
    spec:
      bootstrap:
         dataSecretName: worker-user-data
      clusterName: capi-ocp-aws
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: AWSMachineTemplate
        name: capi-ocp-aws-md-0
      version: v1.18.2

---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSMachineTemplate
metadata:
  name: capi-ocp-aws-md-0
  namespace: default
spec:
  template:
    spec:
      uncompressedUserData: true
      iamInstanceProfile: ...
      instanceType: m5.large
      sshKeyName: ...
      cloudInit:
        secureSecretsBackend: secrets-manager
        insecureSkipSecretsManager: true
      ami:
        id: ...
      subnet:
        id: ...
      additionalSecurityGroups:
        - id: ...
