apiVersion: capi.openshift.io/v1
kind: CAPIDeployment
metadata:
  name: capi-poc
  namespace: ocp-cluster-api

---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineSet
metadata:
  name: capi-poc-ms
  namespace: ocp-cluster-api
spec:
  clusterName: capi-poc
  replicas: 1
  selector:
    matchLabels: 
      test: test
  template:
    metadata:
      labels:
        test: test
    spec:
      bootstrap:
         dataSecretName: worker-user-data
      clusterName: capi-ocp-aws
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: AWSMachineTemplate
        name: capi-poc-template
      version: v1.18.2

---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSMachineTemplate
metadata:
  name: capi-poc-template
  namespace: ocp-cluster-api
spec:
  template:
    spec:
      uncompressedUserData: true
      iamInstanceProfile: ....
      instanceType: m5.large
      cloudInit:
        secureSecretsBackend: secrets-manager
        insecureSkipSecretsManager: true
      ami:
        id: ....
      subnet:
        filters:
        - name: tag:Name
          values:
          - ...
      additionalSecurityGroups:
      - filters:
        - name: tag:Name
          values:
          - ...
