apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: machine-approver
    machine-approver: "true"
  name: machine-approver
  namespace: openshift-cluster-machine-approver
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: machine-approver
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: machine-approver
      name: machine-approver
    spec:
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:9192
        - --upstream=http://127.0.0.1:9191/
        - --tls-cert-file=/etc/tls/private/tls.crt
        - --tls-private-key-file=/etc/tls/private/tls.key
        - --config-file=/etc/kube-rbac-proxy/config-file.yaml
        - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - --logtostderr=true
        - --v=3
        image: registry.ci.openshift.org/ocp/4.8-2021-04-15-062304@sha256:5584994d300418ece9fc5036bd931f560f665c8f77bb5bad27795eb80c6adc20
        imagePullPolicy: IfNotPresent
        name: kube-rbac-proxy
        ports:
        - containerPort: 9192
          hostPort: 9192
          name: https
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/kube-rbac-proxy
          name: auth-proxy-config
        - mountPath: /etc/tls/private
          name: machine-approver-tls
      - args:
        - --config=/var/run/configmaps/config/config.yaml
        - -v=2
        - --logtostderr
        - --apigroup=cluster.x-k8s.io
        command:
        - /usr/bin/machine-approver
        env:
        - name: RELEASE_VERSION
          value: 4.8.0-0.ci-2021-04-15-062304
        - name: METRICS_PORT
          value: "9191"
        image: quay.io/ademicev/origin-cluster-machine-approver:latest
        imagePullPolicy: IfNotPresent
        name: machine-approver-controller
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /var/run/configmaps/config
          name: config
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: machine-approver-sa
      serviceAccountName: machine-approver-sa
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 120
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
        tolerationSeconds: 120
      volumes:
      - configMap:
          defaultMode: 420
          name: kube-rbac-proxy
        name: auth-proxy-config
      - name: machine-approver-tls
        secret:
          defaultMode: 420
          secretName: machine-approver-tls
      - configMap:
          defaultMode: 440
          name: machine-approver-config
          optional: true
        name: config

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cma
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: machine-approver-sa
    namespace: openshift-cluster-machine-approver
