apiVersion: v1
kind: Namespace
metadata:
  labels:
    cluster.x-k8s.io/provider: cluster-api
    control-plane: controller-manager
  name: ocp-cluster-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocp-capi-operator
  namespace: ocp-cluster-api
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/provider: operator
  template:
    metadata:
      labels:
        cluster.x-k8s.io/provider: operator
    spec:
      serviceAccountName: default
      containers:
      - image: quay.io/asalkeld/openshift-cluster-api-operator:latest
        imagePullPolicy: Always
        name: manager
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: ocp-cluster-api
