---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: capi-ocp-vsphere
  name: capi-ocp-vsphere
  namespace: openshift-cluster-api
spec:
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: VSphereCluster
    name: capi-ocp-vsphere
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: VSphereCluster
metadata:
  name: capi-ocp-vsphere
  namespace: openshift-cluster-api
spec:
  server: $VSPHERE_SERVER
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: VSphereMachineTemplate
metadata:
  name: capi-ocp-vsphere
  namespace: openshift-cluster-api
spec:
  template:
    spec:
      cloneMode: linkedClone
      datacenter: $VSPHERE_DATACENTER
      datastore: $VSPHERE_DATASTORE
      diskGiB: 25
      folder: $VSPHERE_FOLDER
      memoryMiB: 8192
      network:
        devices:
        - dhcp4: true
          networkName: $VSPHERE_NETWORK
      numCPUs: 2
      resourcePool: $VSPHERE_RESOURCE_POOL
      server: $VSPHERE_SERVER
      template: $VSPHERE_TEMPLATE
      thumbprint: $VSPHERE_TLS_THUMBPRINT
---
apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineSet
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: capi-ocp-vsphere
  name: capi-ocp-vsphere-md-0
  namespace: openshift-cluster-api
spec:
  clusterName: capi-ocp-vsphere
  replicas: 1
  selector:
    matchLabels: {}
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: capi-ocp-vsphere
    spec:
      bootstrap:
         dataSecretName: worker-user-data
      clusterName: capi-ocp-vsphere
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: VSphereMachineTemplate
        name: capi-ocp-vsphere
      version: v1.18.2
